collections:
  publishers:
    output: true
  plugins:
    output: true

defaults:
  - scope:
      path: ""
      type: "publishers"
    values:
      layout: "publisher"
  - scope:
      path: ""
      type: "plugins"
    values:
      layout: "plugin"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  style: compressed
